name: erex
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.12
  audio_session: ^0.1.18
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # ✅ FIX HERE: use latest stable file_picker
  file_picker: ^8.1.2

  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2   # match Dart 3.x

flutter:
  uses-material-design: true