name: erex
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.12
  audio_session: ^0.1.18
  shared_preferences: ^2.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

  # ✅ Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1

  # ✅ Compatible file_picker
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2   # match Dart 3.x

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png