name: erex
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.12
  audio_session: ^0.1.18
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.7

  # ✅ Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.6

  # ✅ Shared Preferences (required for theme controller + local storage service)
  shared_preferences: ^2.3.2
  audio_video_progress_bar: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/bg.jpg
