// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV39cpcjHgJYCdQpF0S7kqLlEvUpgECe4',
    appId: '1:579230239358:web:b9bd552339b1a14934a62f',
    messagingSenderId: '579230239358',
    projectId: 'music-6e537',
    authDomain: 'music-6e537.firebaseapp.com',
    storageBucket: 'music-6e537.firebasestorage.app',
    measurementId: 'G-4R6RC9JM36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSiiO_mMHapmkZA7JhYQHqOoP0IDTDiQ',
    appId: '1:579230239358:android:b19f28aad4f481eb34a62f',
    messagingSenderId: '579230239358',
    projectId: 'music-6e537',
    storageBucket: 'music-6e537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6qTzYDsGO0HYNbXjTtb1GkWqbc7aApDM',
    appId: '1:579230239358:ios:5014bec8a6890dab34a62f',
    messagingSenderId: '579230239358',
    projectId: 'music-6e537',
    storageBucket: 'music-6e537.firebasestorage.app',
    androidClientId: '579230239358-d5a0t694e643nra3a3tt6fl60jc2pijl.apps.googleusercontent.com',
    iosClientId: '579230239358-l67ivl8ok6jsq0qsi2v2nvstlcg29dhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.erax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6qTzYDsGO0HYNbXjTtb1GkWqbc7aApDM',
    appId: '1:579230239358:ios:5014bec8a6890dab34a62f',
    messagingSenderId: '579230239358',
    projectId: 'music-6e537',
    storageBucket: 'music-6e537.firebasestorage.app',
    androidClientId: '579230239358-d5a0t694e643nra3a3tt6fl60jc2pijl.apps.googleusercontent.com',
    iosClientId: '579230239358-l67ivl8ok6jsq0qsi2v2nvstlcg29dhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.erax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV39cpcjHgJYCdQpF0S7kqLlEvUpgECe4',
    appId: '1:579230239358:web:b9bd552339b1a14934a62f',
    messagingSenderId: '579230239358',
    projectId: 'music-6e537',
    authDomain: 'music-6e537.firebaseapp.com',
    storageBucket: 'music-6e537.firebasestorage.app',
    measurementId: 'G-4R6RC9JM36',
  );
}
